export type Lang = "zh" | "en";

let lang: Lang = new URLSearchParams(location.search).get("lang") === "en" ? "en" : "zh";

export function initialLanguage(): Lang { return lang; }
export function rendererLanguage(): Lang { return lang; }
export function setLanguage(next: Lang): void { lang = next; }

const en: Record<string, string> = {
  "设置": "Settings",
  "返回": "Back",
  "会话状态": "Sessions",
  "连接状态": "Connections",
  "未归档": "Open",
  "已归档": "Archived",
  "已安排": "Scheduled",
  "ChatGPT 桥接": "ChatGPT bridge",
  "Codex 服务": "Codex server",
  "已连接": "Connected",
  "等待浏览器": "Waiting for browser",
  "未配对": "Not paired",
  "检测中": "Detecting",
  "未连接": "Not connected",
  "扩展 v{ext} · 需重载": "Extension v{ext} · reload needed",
  "浏览器扩展为 v{ext}，与主程序 v{app} 不一致，请在 chrome://extensions 中重新加载": "Browser extension is v{ext} but the app is v{app}. Reload it from chrome://extensions",
  "浏览器会话": "Browser sessions",
  "本机任务": "Local tasks",
  "ChatGPT 聊天": "ChatGPT chats",
  "ChatGPT 项目工作": "ChatGPT project work",
  "Codex 任务": "Codex tasks",
  "浏览器桥接已连接": "Browser bridge connected",
  "桥接已断开，当前为只读缓存": "Bridge offline — read-only cache",
  " · {t}同步": " · synced {t} ago",
  "聊天": "Chats",
  "工作": "Work",
  "全部": "All",
  "1 天前": "1 day",
  "1 周前": "1 week",
  "1 个月前": "1 month",
  "半年前": "6 months",
  "最新优先": "Newest first",
  "最早优先": "Oldest first",
  "完整刷新": "Full refresh",
  "同步中…": "Syncing…",
  "打开 ChatGPT": "Open ChatGPT",
  "保存会话": "Save conversations",
  "搜索标题（按 / 聚焦）": "Search titles (press / to focus)",
  "{n} 条结果": "{n} results",
  "最后更新": "Last updated",
  "还没有同步过会话": "Nothing synced yet",
  "还没有读取到任务": "No tasks loaded yet",
  "点击“完整刷新”从本机 App Server 读取任务；若仍为空，请确认已在 Codex 客户端创建过会话。": "Click “Full refresh” to read tasks from the local App Server; if it stays empty, make sure you have created conversations in the Codex client.",
  "点击右上角“完整刷新”，同步当前账号的全部会话。": "Click “Full refresh” to sync all conversations of this account.",
  "桥接已断开。重新打开浏览器中的 ChatGPT 页面，扩展会自动重连并同步。": "Bridge offline. Reopen the ChatGPT tab in your browser — the extension reconnects and syncs automatically.",
  "当前账号还没有项目工作会话；这类会话在项目文件夹或 Codex 中创建。": "No project work conversations on this account yet. They are created inside project folders or Codex.",
  "当前筛选下没有记录": "No records match the current filters",
  "换个搜索关键词，或放宽时间范围再试。": "Try another keyword or widen the time range.",
  "清除筛选": "Clear filters",
  "已选 {n} 条": "{n} selected",
  "只读状态": "Read-only",
  "操作只影响当前筛选与选择": "Operations apply to the current filter and selection",
  "已安排会话请在 ChatGPT 官方页面管理": "Manage scheduled sessions on the ChatGPT web app",
  "全选当前结果": "Select all results",
  "清空选择": "Clear selection",
  "归档": "Archive",
  "恢复": "Restore",
  "永久删除": "Delete forever",
  "停止后续操作": "Stop remaining",
  "单击选中 · 双击打开": "Click to select · double-click to open",
  "项目会话": "Project chat",
  "置顶会话": "Pinned",
  "项目任务": "Project task",
  "非项目任务": "Non-project task",
  "完成：成功 {s}，失败 {f}，未处理 {u}": "Done: {s} succeeded, {f} failed, {u} untouched",
  "操作失败：{msg}": "Operation failed: {msg}",
  "保存失败：{msg}": "Save failed: {msg}",
  "同步或操作超时：浏览器可能正在休眠或网络较慢，请稍后点击“完整刷新”重试。": "The sync or action timed out — the browser may be asleep or the network is slow. Press “Full refresh” to try again.",
  "同步完成：共 {n} 条任务": "Sync finished: {n} tasks",
  "完整校准完成：共 {n} 条任务": "Full calibration finished: {n} tasks",
  "已取消保存": "Save canceled",
  "已保存 {n} 个会话文件到 {dir}，失败 {f} 条": "Saved {n} conversation file(s) to {dir}, {f} failed",
  "已保存 {n} 个任务文件到 {dir}，失败 {f} 条": "Saved {n} task file(s) to {dir}, {f} failed",
  "完整校准完成": "Full calibration finished",
  "后台增量同步完成": "Background incremental sync finished",
  "后台完整校准完成": "Background full calibration finished",
  "当前状态共 {n} 条会话": "{n} conversations in this state",
  "已复制恢复命令，请在终端运行": "Resume command copied — run it in your terminal",
  "统一桌面客户端 · 本机 App Server": "Unified desktop client · local App Server",
  "暂时无法连接 Codex": "Cannot reach Codex",
  "重新检测": "Retry detection",
  "查看安装文档": "Open setup docs",
  "安全浏览器桥接": "Secure browser bridge",
  "复用浏览器中的 ChatGPT 登录": "Reuse your browser's ChatGPT login",
  "无需在管理器中再次登录。在 Chrome/Edge 中加载配套扩展后即会自动完成配对，无需其他操作；也可以点击浏览器工具栏中的扩展，再点“一键连接桌面管理器”。Cookie 和访问令牌始终留在浏览器。": "No separate sign-in needed. Once the companion extension is loaded in Chrome/Edge it pairs automatically; you can also click the extension's toolbar icon and choose “Connect desktop manager”. Cookies and access tokens never leave the browser.",
  "设置与隐私": "Settings & privacy",
  "外观": "Appearance",
  "界面默认跟随系统深色模式自动切换，也可以手动固定为浅色或深色。": "Follows the system dark mode by default, or pin light/dark manually.",
  "跟随系统": "System",
  "浅色": "Light",
  "深色": "Dark",
  "语言": "Language",
  "中文": "中文",
  "English": "English",
  "浏览器桥接": "Browser bridge",
  "已配对，等待浏览器": "Paired, waiting for browser",
  "尚未配对": "Not paired",
  "清除配对": "Clear pairing",
  "打开扩展目录": "Open extension folder",
  "正在清除…": "Clearing…",
  "已清除配对。桌面端运行时，扩展会在后台自动重新配对。": "Pairing cleared. While the desktop app is running, the extension pairs again automatically in the background.",
  "无需手动配对：桌面端运行时，浏览器扩展会自动完成连接。": "No manual pairing needed: while the desktop app is running, the browser extension connects automatically.",
  "扩展目录": "Extension folder",
  "复制路径": "Copy path",
  "已复制": "Copied",
  "复制": "Copy",
  "在终端打开": "Open in terminal",
  "{n} 条消息": "{n} messages",
  "首次使用：在 Chrome/Edge 打开 chrome://extensions，开启“开发者模式”，点击“加载已解压的扩展程序”，选择上面的扩展目录。": "First time: open chrome://extensions in Chrome/Edge, turn on “Developer mode”, click “Load unpacked” and pick the extension folder above.",
  "{t}同步": "synced {t}",
  "{t}完整校准": "full calibration {t}",
  "{n} 条记录": "{n} records",
  "正在连接本机 Codex…": "Connecting to local Codex…",
  "任务": "task",
  "选中任务带有派生子任务，将随主任务一并删除，此操作无法撤销。": "The selected tasks have derived sub-tasks that will be deleted together with them. This cannot be undone.",
  "时间范围": "Time range",
  "ChatGPT": "ChatGPT",
  "未命名任务": "Untitled task",
  "打开": "Open",
  "添加到项目": "Add to project",
  "移出项目": "Remove from project",
  "移出文件夹": "Remove from folder",
  "恢复文件夹分组": "Restore to folder",
  "已移出文件夹": "Removed from folder",
  "已恢复文件夹分组": "Restored to folder",
  "正在加载项目…": "Loading projects…",
  "没有项目，点击重试": "No projects yet — click to retry",
  "会话内容": "Conversation",
  "正在加载会话内容…": "Loading conversation…",
  "浏览器桥接已断开，无法读取会话内容": "The browser bridge is disconnected — conversation content cannot be loaded",
  "在浏览器打开": "Open in browser",
  "关闭": "Close",
  "没有可显示的会话内容": "No message content to display",
  "用户": "User",
  "助手": "Assistant",
  "思考": "Reasoning",
  "工具": "Tool",
  "已添加到项目": "Added to project",
  "已移出项目": "Removed from project",
  "ChatGPT 缓存": "ChatGPT cache",
  "{n} 条记录 · {size}": "{n} records · {size}",
  "正在读取…": "Reading…",
  "清除缓存": "Clear cache",
  "Codex 后端": "Codex backend",
  "Codex 命令": "Codex command",
  "已自动连接 ChatGPT/Codex 桌面客户端内置 App Server": "Connected automatically to the bundled App Server of the ChatGPT/Codex desktop client",
  "手动选择（兜底）": "Choose manually (fallback)",
  "自动更新": "Auto-update",
  "默认自动检查更新": "Check for updates automatically",
  "立即检查": "Check now",
  "下载更新": "Download update",
  "重启安装": "Restart & install",
  "打开下载页": "Open releases page",
  "隐私边界": "Privacy",
  "管理器只保存会话标题、ID、时间和状态。Cookie、访问令牌、正文及 Codex 认证文件不会被读取或复制。": "The manager only stores conversation titles, IDs, timestamps and states. Cookies, access tokens, message bodies and Codex credential files are never read or copied.",
  "连接方式": "How connections work",
  "ChatGPT 会话复用 Chrome/Edge 登录；统一 ChatGPT/Codex 桌面客户端中的 Codex 任务通过自动发现的本机 App Server 读取。两者都不在管理器中重复登录。": "ChatGPT conversations reuse the Chrome/Edge login; Codex tasks come from the automatically discovered local App Server. Neither requires signing in again inside the manager.",
  "运行日志": "Runtime logs",
  "应用运行事件的实时输出，仅保存在本机，用于问题排查。": "Live application events, stored locally for troubleshooting only.",
  "暂无日志": "No log entries",
  "刷新日志": "Refresh",
  "清空日志": "Clear",
  "保存日志": "Save",
  "自动滚动": "Auto-scroll",
  "已保存到 {path}": "Saved to {path}",
  "将永久删除 {n} 条会话": "Permanently delete {n} conversations",
  "将永久删除 {n} 条任务": "Permanently delete {n} tasks",
  "此操作无法撤销，删除后无法恢复。": "This cannot be undone.",
  "其余 {n} 条": "…and {n} more",
  "输入 {n} 以确认": "Type {n} to confirm",
  "取消": "Cancel",
  "确认删除": "Delete forever",
  "刚刚": "just now",
  "{n} 分钟前": "{n} min ago",
  "{n} 小时前": "{n} h ago",
  "{n} 天前": "{n} d ago",
  "项目任务 · ": "Project task · ",
  "非项目任务 · ": "Non-project task · ",
  "暂停日志": "Pause log",
  "恢复日志": "Resume log",
  "日志已暂停": "Log stream paused",
  "会话": "conversation(s)",
  "返回上一页面": "Back to previous page",
  "App Server 已连接": "App Server connected",
  "桥接已连接": "Bridge connected",
  "语言 / Language": "Language",
  "搜索标题": "Search titles",
  "会话类型": "Conversation type",
  "排序": "Sort",
  "未知": "unknown",
  "运行中": "Running",
  "部分任务不存在或仍在运行，无法删除": "Some tasks are missing or still running and cannot be deleted",
  "同时删除 {n} 个派生任务": "Also delete {n} derived tasks",
  "永久删除 {n} 条{unit}": "Permanently delete {n} {unit}",
  "{n} 条": "{n} items",
  "正在自动检测统一桌面客户端…": "Detecting the unified desktop client automatically…",
  "操作失败": "Operation failed",
  "保存失败": "Save failed",
  "同步完成": "Sync finished",
  "{n} 条失败": "{n} failed",
  "已保存 {n} 个会话文件": "Saved {n} conversation file(s)",
  "已保存 {n} 个任务文件": "Saved {n} task file(s)"
};

export function t(text: string, params?: Record<string, string | number>): string {
  let out = lang === "en" ? en[text] ?? text : text;
  if (params) for (const [key, value] of Object.entries(params)) out = out.replaceAll(`{${key}}`, String(value));
  return out;
}
